### ISSUE TITLE
TypeError: missing arguments with ALBL strategy

### ISSUE THREAD

**Issue by kaushikpavani** [ej0cl6/deep-active-learning#1]
There is a bug in deep-active-learning/query_strategies/active_learning_by_learning.py line 9. 

self.strategy_list.append(RandomSampling(X, Y, idxs_lb, args))

I got the error: TypeError: __init__() missing 2 required positional arguments: 'handler' and 'args'

The fix should be: 

self.strategy_list.append(RandomSampling(X, Y, idxs_lb, net, handler, args))

**Comment by Arrcil** [comment]
About GPU， do you use gpu to run or cpu？If we want to use gpu， where should we change the code？

**Comment by ej0cl6** [comment]
> 

Thanks for finding this bug. The whole repo has been updated and now ALBL is temporarily not supported. So let me close this issue first.

**Comment by ej0cl6** [comment]
> There is a bug in deep-active-learning/query_strategies/active_learning_by_learning.py line 9.
> 
> self.strategy_list.append(RandomSampling(X, Y, idxs_lb, args))
> 
> I got the error: TypeError: **init**() missing 2 required positional arguments: 'handler' and 'args'
> 
> The fix should be:
> 
> self.strategy_list.append(RandomSampling(X, Y, idxs_lb, net, handler, args))

Thanks for finding this bug. The whole repo has been updated and now ALBL is temporarily not supported. So let me close this issue first.
