### ISSUE TITLE
Mapping between paper names to python class

### ISSUE THREAD

**Issue by kobybibas** [ej0cl6/deep-active-learning#11]
Hey, Thanks for this awesome repository.
A quick question, is there a mapping between the paper names to the python code classes?
Specifically I'm interested in ''ACTIVE LEARNING FOR CONVOLUTIONAL NEURAL
NETWORKS: A CORE-SET APPROACH`` which supposes to be one of these: 
"RandomSampling", "LeastConfidence", "MarginSampling", "EntropySampling", "LeastConfidenceDropout", "MarginSamplingDropout", "EntropySamplingDropout", "KMeansSampling", "KCenterGreedy", "BALDDropout", "AdversarialBIM", "AdversarialDeepFool",

**Comment by ej0cl6** [comment]
Hi, thanks for your interest. Currently we have approximated version of CoreSet (k-means and k-centers). The main reason for the original CoreSet is that it requires an external solver which is not free and it's hard to combine the external solver with the current code smoothly (many people asked about the usage). So I decided to remove it from the package. However, you can still find the implementation by the original authors here: https://github.com/ozansener/active_learning_coreset
Or you can check the old commit in this repository. I believe it's till there, but the overall training framework now is a bit different.

**Comment by kobybibas** [comment]
Ok, thanks a lot!
