### ISSUE TITLE
Can this pipeline be applied to any deep learning model?

### ISSUE THREAD

**Issue by Tony363** [ej0cl6/deep-active-learning#12]
Hey there,

I'm looking to explore deep learning with active learning semi automated labels for a video classification project i have. I currently use a Bidirectional LSTM and may look to explore transformers, gradient boosted decision trees and SVMs as well. For LSTMs and transformers, is it possible for me to use my LSTM model with the current framework?

- Tony

**Comment by ej0cl6** [comment]
Yes, you can use those models by adding them to `nets.py` and update the `get_net` function in `utils.py`.
