### ISSUE TITLE
Couldn't find coreset implementation

### ISSUE THREAD

**Issue by bryanwong17** [ej0cl6/deep-active-learning#14]
Hi,

I couldn't find the coreset implementation in your code. How can I find it?

Thanks!

**Comment by ej0cl6** [comment]
Hi, thanks for asking. The main reason is that CoreSet requires an external solver which is not free and it's hard to combine the external solver with the current code smoothly (many people asked about the usage). So I decided to remove it from the package. However, you can still find the implementation by the original authors here: https://github.com/ozansener/active_learning_coreset
