### ISSUE TITLE
Is there a mistake in Deepfool implementation?

### ISSUE THREAD

**Issue by saifullah3396** [ej0cl6/deep-active-learning#15]
I believe there is a mistake in this line in adversarial_deepfool.py 
if value_i < value_l:
    ri = value_i/np.linalg.norm(wi.numpy().flatten()) * wi
    value_l = value_i # <--- this line should be added here since otherwise,t value_i is just always the last value in the for loop?

**Comment by ej0cl6** [comment]
Thanks for pointing out this. Just fixed it.
