### ISSUE TITLE
Error in random_sampling.py

### ISSUE THREAD

**Issue by EveWYT** [ej0cl6/deep-active-learning#3]
The query function use 'return np.random.choice(np.where(self.idxs_lb==0)[0], n)' to generate new indexes, but without 'replace=False', it cannnot generate exact 1000 indexes each iteration. To compare with other query strategies with same labeled number, it should be 'return np.random.choice(np.where(self.idxs_lb==0)[0], n, replace=False)'

**Comment by ej0cl6** [comment]
We have fixed this issue. Thanks for you help!
