### ISSUE TITLE
Gurobi License

### ISSUE THREAD

**Issue by vietth-bka** [ej0cl6/deep-active-learning#4]
Thanks for your incredible lines of code. There are no problems until I run model.optimize() in file full_solver_gurobi.py, it raises error: 'GurobiError: Model too large for size-limited license; visit https://www.gurobi.com/free-trial for a full license'.
Gurobi seem not to be free with large size models (because I ran 35000 vectors size of 512) I just want to quickly reproduce the reported results of the paper but not any commercial purposes.
Is there any other way to reproduce the results of Core-Set [3] paper or to get the free Gurobi license?

**Comment by ej0cl6** [comment]
Currently, our package has been updated and does not support core-set method anymore. Please refer to the original repo (https://github.com/ozansener/active_learning_coreset) of core-set method.
