### ISSUE TITLE
CoreSet AL algorithm

### ISSUE THREAD

**Issue by luuyin** [ej0cl6/deep-active-learning#5]
Hi, thanks for your excellent codes.  I have a question regarding to the CoreSet AL algorithm. In your previews version, there is this algorithm but now it is gone. May I know the reason? Thanks a lot in advance!!

**Comment by ej0cl6** [comment]
Hi, thanks for asking. The main reason is that CoreSet requires an external solver which is not free and it's hard to combine the external solver with the current code smoothly (many people asked about the usage). So I decided to remove it from the package. However, you can still find the implementation by the original authors here: https://github.com/ozansener/active_learning_coreset
