### ISSUE TITLE
Asking the probability formula if its a binary problem

### ISSUE THREAD

**Issue by leocd91** [ej0cl6/deep-active-learning#7]
Suppose it's a binary problem, did I do it right if I just sort it directly the prob or uncertainties result?

**Comment by ej0cl6** [comment]
This is what we do in the current version DeepAL. This greedy approach usually works in practice. Of course there must be some better ways to handle the batch scoring but currently we do not focus on it.

**Comment by leocd91** [comment]
ah, i see, I get it after seeing your code. thanks.

**Comment by leocd91** [comment]
hi @ej0cl6 , why KCenterGreedy use training data to get the `embeddings`? why there's no unlabelled data being included there?

**Comment by ej0cl6** [comment]
It is used for learning the centers.
